# Lab Date:16-02-2023

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [19]:
#loading data
data = pd.read_csv('sales_country_wise.csv')
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

In [24]:
#Before handling missing data
print(x)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Gremany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [27]:
#taking care of missing data using imputer from sklearn
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy = 'mean')
imputer.fit(x[:,1:3])
x[:,1:3] = imputer.transform(x[:,1:3])
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Gremany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# Week 2

In [29]:
#Encoding categorical data
#Encoding independent varibles only
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[0])],remainder='passthrough')

In [31]:
x=np.array(ct.fit_transform(x))
print(x)

[[0.0 1.0 0.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 0.0 37.0 67000.0]]


In [35]:
#splitting the dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)
print("training data")
print(x_train)
print(y_train)
print("Testing data")
print(x_test)
print(y_test)

[[1.0 0.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 0.0 35.0 58000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes']
Testing dat
[[1.0 0.0 1.0 0.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 0.0 37.0 67000.0]]
['No' 'Yes']
